export const STAGE_DEFINITIONS = [
  {
    id: 0,
    name: 'Original',
    label: 'SQL (原文)',
    description: '入力されたSQLクエリそのまま',
    language: 'sql' as const,
    color: '#ef4444',
    icon: '📝',
    targetMetric: null as string | null,
  },
  {
    id: 1,
    name: 'Flatten',
    label: 'Flatten (ネスト解消)',
    description: 'サブクエリ・CTEのJOINフラット化。左深木JOIN→線形チェーン',
    language: 'wvlet' as const,
    color: '#f97316',
    icon: '🔨',
    targetMetric: 'SN',
  },
  {
    id: 2,
    name: 'Flow',
    label: 'Flow (順序最適化)',
    description: 'SELECT-first → FROM-first への構文順序変更',
    language: 'wvlet' as const,
    color: '#eab308',
    icon: '🔄',
    targetMetric: 'SSOA',
  },
  {
    id: 3,
    name: 'Deduplicate',
    label: 'Deduplicate (重複排除)',
    description: 'Anti-Unificationによる共通パターン抽出→モデル化',
    language: 'wvlet' as const,
    color: '#22c55e',
    icon: '♻️',
    targetMetric: 'DRY',
  },
  {
    id: 4,
    name: 'Final',
    label: 'Wvlet (最終)',
    description: '全最適化適用後の最終Wvletコード',
    language: 'wvlet' as const,
    color: '#3b82f6',
    icon: '✨',
    targetMetric: null,
  },
] as const;
